---
- name: Download OKD binaries
  get_url:
    url: "https://github.com/openshift/origin/releases/download/v{{OKD_VERSION}}/openshift-origin-server-v{{OKD_VERSION}}-0cbc58b-linux-64bit.tar.gz"
    dest: /tmp

- name: Unzip OKD libraries
  unarchive:
    src: /tmp/openshift-origin-server-v{{OKD_VERSION}}-0cbc58b-linux-64bit.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy oc libs to PATH
  shell: cp -r /tmp/openshift-origin-server-v{{OKD_VERSION}}-0cbc58b-linux-64bit/* /usr/local/bin

- name: OC cluster UP
  command: oc cluster up
