---
- name: Get current public IP
  command: "curl -s ipinfo.io/ip"
  register: public_ip

- name: Get internal IP
  command: "ip route get 8.8.8.8 | awk '{print $NF; exit}'"
  register: private_ip

- name: set domain value
  set_fact:
    DOMAIN: "{{ public_ip.stdout }}"

- name: set IP value
  set_fact:
    IP: "{{ private_ip.stdout }}"

- name: Get the openshift-ansible repo
  git:
    repo: "https://github.com/openshift/openshift-ansible.git"
    dest: /tmp/openshift-ansible
    version: "rebase-{{ VERSION }}"
    depth: 1
    clone: yes

- name: Updating /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    force: yes
    mode: 0755

- name: Updating ansible inventory
  template:
    src: inventory.j2
    dest: /tmp/inventory.ini
    force: yes
    mode: 0755

- name: Creating folder for master htaceess
  file:
    path: /etc/origin/master
    state: directory

- name: Create htpasswd file
  file:
    path: /etc/origin/master/htpasswd
    state: touch
    mode: 0644

- name: Run Openshift Prerequisites.yml
  command: "ansible-playbook -i /tmp/inventory.ini /tmp/openshift-ansible/playbooks/prerequisites.yml"

- name: Run Openshift Deploy_cluster.yml
  command: "ansible-playbook -i /tmp/inventory.ini /tmp/openshift-ansible/playbooks/deploy_cluster.yml"

- name: htpasswd file creation
  htpasswd:
    path: /etc/origin/master/htpasswd
    name: "{{ USERNAME }}"
    password: "{{ PASSWORD }}"
    owner: root
    mode: 0640

- name: Updating oc adm policy
  command: "oc adm policy add-cluster-role-to-user cluster-admin {{USERNAME}}"
