---
- name: package epel-release upgrade
  yum:
    name:
      - epel-release

- name: Install required system packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker Repository
  yum_repository:
    name: docker-ce
    description: Docker CE Repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    state: present

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Insert docker INSECURE_REG line
  lineinfile:
    path: /etc/sysconfig/docker
    state: present
    insertafter: EOF
    line: "INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'"
  notify: Restart docker

- name: Determine Docker network Bridge Subnet
  docker_network_info:
    name: bridge
  register: docker_network

- name: Print information about network
  debug:
    var: docker_network.network
  when: docker_network.exists
