---
- name: Disable swap
  swapoff: {}

- name: Enable IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: "/etc/sysctl.d/99-openshift.conf"
    reload: yes

- name: package epel-release upgrade
  yum:
    name:
      - epel-release

- name: Install required system packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: "docker-ce-edge"
    option: enabled
    value: 0

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: "docker-ce-test"
    option: enabled
    value: 0

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Insert docker INSECURE_REG line
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0755
  notify: Restart docker

- name: Determine Docker network Bridge Subnet
  docker_network_info:
    name: bridge
  register: docker_network

- name: Print information about network
  debug:
    var: docker_network.network
  when: docker_network.exists
