---
- name: Disable swap
  shell: |
    swapoff -a

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Enable IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: "/etc/sysctl.d/99-openshift.conf"
    reload: yes

- name: package epel-release upgrade
  yum:
    name:
      - epel-release

- name: Install required system packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - firewalld
    state: present

- name: Add Docker Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: "docker-ce-edge"
    option: enabled
    value: 0

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: "docker-ce-test"
    option: enabled
    value: 0

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Insert docker INSECURE_REG line
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0755
  notify:
    - restart docker

- name: restart docker
  service:
    name: docker
    state: restarted

- name: Determine Docker network Bridge Subnet
  docker_network_info:
    name: bridge
  register: docker_network

- name: Set Subnet value of docker network
  set_fact:
    subnet: docker_network.network.IPAM.Config | map(attribute="Subnet") | list | join('\n')
  when: docker_network.exists

- name: firewalld zone rules - create zone
  firewalld:
    zone: dockerc
    state: present
    permanent: yes

- name: firewalld zone rules - add source
  firewalld:
    source: "{{ subnet }}"
    zone: dockerc
    permanent: yes
    state: enabled

- name: firewalld zone rules - add tcp ports
  firewalld:
    port: 8081/tcp
    permanent: yes
    state: enabled

- name: firewalld zone rules - add udp ports
  firewalld:
    port: 53/udp
    permanent: yes
    state: enabled

- name: firewalld zone rules - add tcp ports
  firewalld:
    port: 8053/udp
    permanent: yes
    state: enabled
